# **1. Import Libraries**

In [61]:
import pandas as pd # to work with dataframes
import numpy as np # to work with arrays and perform mathematical operations
import glob # to import multiple files at once
import os # to create a folder

# **2. Data Preprocessing**

**Import csv files**

In [ ]:
# Claimant Count
claimant_files = sorted(glob.glob("../data/bronze/*/*claimant_counts*.csv")) # glob.glob returns a list of file paths matching the pattern, sorted to maintain order
claimant = pd.concat([pd.read_csv(file) for file in claimant_files], ignore_index=True) # ignore_index to reset the index after concatenation

# Health
health_files = sorted(glob.glob("../data/bronze/*/*health*.csv"))
health = pd.concat([pd.read_csv(file) for file in health_files], ignore_index=True)

In [20]:
claimant.head() # check the first 5 rows of the dataframe to understand the data

   area_code                  area_name   pop  claimant_rate  claimant_count
0  E01000001        City of London 001A  1453       0.099794             145
1  E01000002        City of London 001B  1414       0.102546             145
2  E01000003        City of London 001C  1592       0.386307             615
3  E01000005        City of London 001E  1751       0.445460             780
4  E01000006  Barking and Dagenham 016A  1583       0.701200            1110

In [21]:
health.head()

,area_code,area_name,pop,AF_prevalence_rate,AF_afflicted,AST_prevalence_rate,AST_afflicted,CAN_prevalence_rate,CAN_afflicted,CHD_prevalence_rate,...,OST_prevalence_rate,OST_afflicted,PAD_prevalence_rate,PAD_afflicted,PC_prevalence_rate,PC_afflicted,RA_prevalence_rate,RA_afflicted,STIA_prevalence_rate,STIA_afflicted
0,E01000001,City of London 001A,1453,0.012116,17.604814,0.035175,51.109454,0.021126,30.696221,0.016198,...,0.001633,2.373423,0.003331,4.839869,0.003133,4.552920,0.004273,6.208687,0.009583,13.924394
1,E01000002,City of London 001B,1414,0.012642,17.875873,0.034753,49.140221,0.021662,30.630014,0.016508,...,0.001755,2.481464,0.003408,4.819109,0.003227,4.563124,0.004399,6.219600,0.009774,13.819994
2,E01000003,City of London 001C,1592,0.011004,17.518245,0.036276,57.751737,0.019646,31.277001,0.014895,...,0.001272,2.024335,0.003546,5.645832,0.003133,4.988190,0.003825,6.089937,0.009129,14.532581
3,E01000005,City of London 001E,1751,0.008806,15.419052,0.035617,62.365225,0.016835,29.477697,0.016930,...,0.001427,2.499068,0.002762,4.836149,0.002280,3.991445,0.004218,7.384987,0.008819,15.442882
4,E01000006,Barking and Dagenham 016A,1583,0.008504,13.461946,0.051032,80.783938,0.016011,25.344752,0.019437,...,0.001140,1.804233,0.002575,4.076790,0.001803,2.853478,0.006309,9.987424,0.011146,17.644295

In [22]:
claimant.columns # check the columns of the dataframe to understand the data and identify any issues with the data

Index(['area_code', 'area_name', 'pop', 'claimant_rate', 'claimant_count'], dtype='object')

In [23]:
health.columns

Index(['area_code', 'area_name', 'pop', 'AF_prevalence_rate', 'AF_afflicted',
       'AST_prevalence_rate', 'AST_afflicted', 'CAN_prevalence_rate',
       'CAN_afflicted', 'CHD_prevalence_rate', 'CHD_afflicted',
       'CKD_prevalence_rate', 'CKD_afflicted', 'COPD_prevalence_rate',
       'COPD_afflicted', 'DEM_prevalence_rate', 'DEM_afflicted',
       'DEP_prevalence_rate', 'DEP_afflicted', 'DM_prevalence_rate',
       'DM_afflicted', 'EP_prevalence_rate', 'EP_afflicted',
       'HF_prevalence_rate', 'HF_afflicted', 'HYP_prevalence_rate',
       'HYP_afflicted', 'LD_prevalence_rate', 'LD_afflicted',
       'MH_prevalence_rate', 'MH_afflicted', 'NDH_prevalence_rate',
       'NDH_afflicted', 'OB_prevalence_rate', 'OB_afflicted',
       'OST_prevalence_rate', 'OST_afflicted', 'PAD_prevalence_rate',
       'PAD_afflicted', 'PC_prevalence_rate', 'PC_afflicted',
       'RA_prevalence_rate', 'RA_afflicted', 'STIA_prevalence_rate',
       'STIA_afflicted'],
      dtype='object')

In [24]:
claimant.info() # check the info of the dataframe to understand the data types and null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65688 entries, 0 to 65687
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   area_code       65688 non-null  object
 1   area_name       65688 non-null  object
 2   pop             65688 non-null  int64
 3   claimant_rate   65688 non-null  float64
 4   claimant_count  65688 non-null  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 2.5+ MB

**Standardise column names**

In [25]:
dfs = [claimant, health]

for df in dfs:
    df.columns = (
        df.columns
        .str.strip() # remove any leading or trailing whitespace from the column names
        .str.lower() # convert the column names to lowercase
        .str.replace(" ", "_") # replace any spaces in the column names with underscores 
    )

In [26]:
claimant.columns

Index(['area_code', 'area_name', 'pop', 'claimant_rate', 'claimant_count'], dtype='object')

In [27]:
health.columns

Index(['area_code', 'area_name', 'pop', 'af_prevalence_rate', 'af_afflicted',
       'ast_prevalence_rate', 'ast_afflicted', 'can_prevalence_rate',
       'can_afflicted', 'chd_prevalence_rate', 'chd_afflicted',
       'ckd_prevalence_rate', 'ckd_afflicted', 'copd_prevalence_rate',
       'copd_afflicted', 'dem_prevalence_rate', 'dem_afflicted',
       'dep_prevalence_rate', 'dep_afflicted', 'dm_prevalence_rate',
       'dm_afflicted', 'ep_prevalence_rate', 'ep_afflicted',
       'hf_prevalence_rate', 'hf_afflicted', 'hyp_prevalence_rate',
       'hyp_afflicted', 'ld_prevalence_rate', 'ld_afflicted',
       'mh_prevalence_rate', 'mh_afflicted', 'ndh_prevalence_rate',
       'ndh_afflicted', 'ob_prevalence_rate', 'ob_afflicted',
       'ost_prevalence_rate', 'ost_afflicted', 'pad_prevalence_rate',
       'pad_afflicted', 'pc_prevalence_rate', 'pc_afflicted',
       'ra_prevalence_rate', 'ra_afflicted', 'stia_prevalence_rate',
       'stia_afflicted'],
      dtype='object')

**Drop Unrequired Columns**

In [28]:
claimant = claimant[
    ["area_code", "pop", "claimant_rate"]
]

claimant.columns

Index(['area_code', 'pop', 'claimant_rate'], dtype='object')

In [29]:
health = health[
    [col for col in health.columns 
     if "prevalence_rate" in col 
     or col in ["area_code"]]
]

health.columns

Index(['area_code', 'af_prevalence_rate', 'ast_prevalence_rate',
       'can_prevalence_rate', 'chd_prevalence_rate', 'ckd_prevalence_rate',
       'copd_prevalence_rate', 'dem_prevalence_rate', 'dep_prevalence_rate',
       'dm_prevalence_rate', 'ep_prevalence_rate', 'hf_prevalence_rate',
       'hyp_prevalence_rate', 'ld_prevalence_rate', 'mh_prevalence_rate',
       'ndh_prevalence_rate', 'ob_prevalence_rate', 'ost_prevalence_rate',
       'pad_prevalence_rate', 'pc_prevalence_rate', 'ra_prevalence_rate',
       'stia_prevalence_rate'],
      dtype='object')

**Check for Null Values**

In [30]:
display(claimant.isnull().sum(), round(claimant.isnull().mean(), 2)) # check the number of null values in each column and the percentage of null values in each column

area_code        0
pop              0
claimant_rate    0
dtype: int64

area_code        0.0
pop              0.0
claimant_rate    0.0
dtype: float64

In [31]:
display(health.isnull().sum(), round(health.isnull().mean(), 2))

area_code               0
af_prevalence_rate      0
ast_prevalence_rate     0
can_prevalence_rate     0
chd_prevalence_rate     0
ckd_prevalence_rate     0
copd_prevalence_rate    0
dem_prevalence_rate     0
dep_prevalence_rate     0
dm_prevalence_rate      0
ep_prevalence_rate      0
hf_prevalence_rate      0
hyp_prevalence_rate     0
ld_prevalence_rate      0
mh_prevalence_rate      0
ndh_prevalence_rate     0
ob_prevalence_rate      0
ost_prevalence_rate     0
pad_prevalence_rate     0
pc_prevalence_rate      0
ra_prevalence_rate      0
stia_prevalence_rate    0
dtype: int64

area_code               0.0
af_prevalence_rate      0.0
ast_prevalence_rate     0.0
can_prevalence_rate     0.0
chd_prevalence_rate     0.0
ckd_prevalence_rate     0.0
copd_prevalence_rate    0.0
dem_prevalence_rate     0.0
dep_prevalence_rate     0.0
dm_prevalence_rate      0.0
ep_prevalence_rate      0.0
hf_prevalence_rate      0.0
hyp_prevalence_rate     0.0
ld_prevalence_rate      0.0
mh_prevalence_rate      0.0
ndh_prevalence_rate     0.0
ob_prevalence_rate      0.0
ost_prevalence_rate     0.0
pad_prevalence_rate     0.0
pc_prevalence_rate      0.0
ra_prevalence_rate      0.0
stia_prevalence_rate    0.0
dtype: float64

**Remove duplicates**

In [47]:
# show rows with duplicates
claimant[claimant.duplicated(subset=["area_code"], keep=False)].sort_values(by="area_code").head() # check the rows with duplicate crime_id to understand if there are any patterns in the duplicates

       area_code   pop  claimant_rate
0      E01000001  1453       0.099794
32844  E01000001  1453       0.092911
32845  E01000002  1414       0.084866
1      E01000002  1414       0.102546
32846  E01000003  1592       0.414573

In [48]:
# averaging duplicates
claimant = (
    claimant
    .groupby(["area_code", "pop"], as_index=False)
    .agg({"claimant_rate": "mean"})
)

claimant["area_code"].duplicated().sum() # validate

np.int64(0)

In [51]:
health[health.duplicated(subset=["area_code"], keep=False)].sort_values(by="area_code").head()

,area_code,af_prevalence_rate,ast_prevalence_rate,can_prevalence_rate,chd_prevalence_rate,ckd_prevalence_rate,copd_prevalence_rate,dem_prevalence_rate,dep_prevalence_rate,dm_prevalence_rate,...,hyp_prevalence_rate,ld_prevalence_rate,mh_prevalence_rate,ndh_prevalence_rate,ob_prevalence_rate,ost_prevalence_rate,pad_prevalence_rate,pc_prevalence_rate,ra_prevalence_rate,stia_prevalence_rate
0,E01000001,0.012116,0.035175,0.021126,0.016198,0.021726,0.008768,0.002195,0.078826,0.029574,...,0.085872,0.001277,0.009579,0.014849,0.028460,0.001633,0.003331,0.003133,0.004273,0.009583
32844,E01000001,0.011520,0.033501,0.021034,0.015086,0.018877,0.007823,0.002181,0.078471,0.028684,...,0.079425,0.001361,0.009060,0.014747,0.036162,0.001443,0.002958,0.003085,0.003870,0.008684
32845,E01000002,0.011953,0.033121,0.021530,0.015313,0.019571,0.007774,0.002228,0.075852,0.028389,...,0.080575,0.001296,0.008866,0.013746,0.035517,0.001523,0.003048,0.003162,0.003977,0.008840
1,E01000002,0.012642,0.034753,0.021662,0.016508,0.022660,0.008737,0.002249,0.076197,0.029323,...,0.087426,0.001166,0.009367,0.013701,0.028309,0.001755,0.003408,0.003227,0.004399,0.009774
32846,E01000003,0.010242,0.035084,0.019506,0.013575,0.015567,0.011153,0.002574,0.088217,0.031068,...,0.075843,0.002149,0.009688,0.019181,0.042043,0.001087,0.003067,0.002629,0.003578,0.008573

In [52]:
health = (
    health
    .groupby("area_code", as_index=False)
    .mean()
)

health["area_code"].duplicated().sum()

np.int64(0)

**Feature Engineering**

In [56]:
# add all the prevelance rate

total_health_prevelance_rate = [col for col in health.columns if col.endswith("_prevalence_rate")]

# Create total column
health["total_prevalence_rate"] = health[total_health_prevelance_rate].sum(axis=1)

# Keep only area_code and total
health = health[
    ["area_code", "total_prevalence_rate"]
]

health.head()

   area_code  total_prevalence_rate
0  E01000001               1.173288
1  E01000002               1.170547
2  E01000003               1.222848
3  E01000005               1.126803
4  E01000006               1.609504

In [58]:
claimant.dtypes

area_code         object
pop                int64
claimant_rate    float64
dtype: object

In [59]:
health.dtypes

area_code                 object
total_prevalence_rate    float64
dtype: object

**Export**

In [64]:
# Create the directory if it already doesn't exist
os.makedirs("../data/silver", exist_ok=True)

dfs = {
    "claimant_clean": claimant,
    "health_clean": health
}

for name, df in dfs.items():
    df.to_csv(f"../data/silver/{name}.csv", index=False)