# **1. Import Libraries**

In [59]:
import pandas as pd # to work with dataframes
import numpy as np # to work with arrays and perform mathematical operations
import glob # to import multiple files at once
import os # to create a folder

# **2. Data Preprocessing**

**Import csv files**

In [60]:
def load_dataset(pattern):
    """Load csv files from the path you pass into pattern"""
    files = sorted(glob.glob(pattern))

    if not files:
        print(f"No files found for: {pattern}")
        return pd.DataFrame()

    return pd.concat(
        [pd.read_csv(file) for file in files],
        ignore_index=True
    )

In [61]:
claimant = load_dataset("../data/bronze/*/*claimant_counts*.csv")
health = load_dataset("../data/bronze/*/*health*.csv")
crime = load_dataset("../data/bronze/*/*crime*.csv")

In [62]:
print(claimant.shape)
print(health.shape)
print(crime.shape)

(32844, 5)
(32844, 45)
(32844, 31)

In [63]:
claimant.head() # check the first 5 rows of the dataframe to understand the data

   area_code                  area_name   pop  claimant_rate  claimant_count
0  E01000001        City of London 001A  1453       0.099794             145
1  E01000002        City of London 001B  1414       0.102546             145
2  E01000003        City of London 001C  1592       0.386307             615
3  E01000005        City of London 001E  1751       0.445460             780
4  E01000006  Barking and Dagenham 016A  1583       0.701200            1110

In [64]:
health.head()

,area_code,area_name,pop,AF_prevalence_rate,AF_afflicted,AST_prevalence_rate,AST_afflicted,CAN_prevalence_rate,CAN_afflicted,CHD_prevalence_rate,...,OST_prevalence_rate,OST_afflicted,PAD_prevalence_rate,PAD_afflicted,PC_prevalence_rate,PC_afflicted,RA_prevalence_rate,RA_afflicted,STIA_prevalence_rate,STIA_afflicted
0,E01000001,City of London 001A,1453,0.012116,17.604814,0.035175,51.109454,0.021126,30.696221,0.016198,...,0.001633,2.373423,0.003331,4.839869,0.003133,4.552920,0.004273,6.208687,0.009583,13.924394
1,E01000002,City of London 001B,1414,0.012642,17.875873,0.034753,49.140221,0.021662,30.630014,0.016508,...,0.001755,2.481464,0.003408,4.819109,0.003227,4.563124,0.004399,6.219600,0.009774,13.819994
2,E01000003,City of London 001C,1592,0.011004,17.518245,0.036276,57.751737,0.019646,31.277001,0.014895,...,0.001272,2.024335,0.003546,5.645832,0.003133,4.988190,0.003825,6.089937,0.009129,14.532581
3,E01000005,City of London 001E,1751,0.008806,15.419052,0.035617,62.365225,0.016835,29.477697,0.016930,...,0.001427,2.499068,0.002762,4.836149,0.002280,3.991445,0.004218,7.384987,0.008819,15.442882
4,E01000006,Barking and Dagenham 016A,1583,0.008504,13.461946,0.051032,80.783938,0.016011,25.344752,0.019437,...,0.001140,1.804233,0.002575,4.076790,0.001803,2.853478,0.006309,9.987424,0.011146,17.644295

In [65]:
crime.head()

,area_code,area_name,pop,anti-social_behaviour_rate,anti-social_behaviour,bicycle_theft_rate,bicycle_theft,burglary_rate,burglary,criminal_damage_and_arson_rate,...,robbery_rate,robbery,shoplifting_rate,shoplifting,theft_from_the_person_rate,theft_from_the_person,vehicle_crime_rate,vehicle_crime,violence_and_sexual_offences_rate,violence_and_sexual_offences
0,E01000001,City of London 001A,1453,0.021335,31,0.012388,18,0.003441,5,0.006882,...,0.004129,6,0.008259,12,0.017894,26,0.024088,35,0.013076,19
1,E01000002,City of London 001B,1414,0.041018,58,0.030410,43,0.004243,6,0.009194,...,0.001414,2,0.009901,14,0.018388,26,0.004243,6,0.031825,45
2,E01000003,City of London 001C,1592,0.021357,34,0.002513,4,0.000000,0,0.006281,...,0.000000,0,0.000000,0,0.006281,10,0.001256,2,0.005025,8
3,E01000005,City of London 001E,1751,0.057110,100,0.027413,48,0.017133,30,0.012564,...,0.007424,13,0.013706,24,0.010851,19,0.015420,27,0.046830,82
4,E01000006,Barking and Dagenham 016A,1583,0.033481,53,0.000000,0,0.002527,4,0.003159,...,0.001895,3,0.000000,0,0.001895,3,0.006317,10,0.024005,38

**Standardise column names**

In [66]:
dfs = [claimant, health, crime]

for df in dfs:
    df.columns = (
        df.columns
        .str.strip() # remove any leading or trailing whitespace from the column names
        .str.lower() # convert the column names to lowercase
        .str.replace(" ", "_") # replace any spaces in the column names with underscores 
    )

    print(df.columns)

Index(['area_code', 'area_name', 'pop', 'claimant_rate', 'claimant_count'], dtype='object')
Index(['area_code', 'area_name', 'pop', 'af_prevalence_rate', 'af_afflicted',
       'ast_prevalence_rate', 'ast_afflicted', 'can_prevalence_rate',
       'can_afflicted', 'chd_prevalence_rate', 'chd_afflicted',
       'ckd_prevalence_rate', 'ckd_afflicted', 'copd_prevalence_rate',
       'copd_afflicted', 'dem_prevalence_rate', 'dem_afflicted',
       'dep_prevalence_rate', 'dep_afflicted', 'dm_prevalence_rate',
       'dm_afflicted', 'ep_prevalence_rate', 'ep_afflicted',
       'hf_prevalence_rate', 'hf_afflicted', 'hyp_prevalence_rate',
       'hyp_afflicted', 'ld_prevalence_rate', 'ld_afflicted',
       'mh_prevalence_rate', 'mh_afflicted', 'ndh_prevalence_rate',
       'ndh_afflicted', 'ob_prevalence_rate', 'ob_afflicted',
       'ost_prevalence_rate', 'ost_afflicted', 'pad_prevalence_rate',
       'pad_afflicted', 'pc_prevalence_rate', 'pc_afflicted',
       'ra_prevalence_rate', 'ra_afflicted', 'stia_prevalence_rate',
       'stia_afflicted'],
      dtype='object')
Index(['area_code', 'area_name', 'pop', 'anti-social_behaviour_rate',
       'anti-social_behaviour', 'bicycle_theft_rate', 'bicycle_theft',
       'burglary_rate', 'burglary', 'criminal_damage_and_arson_rate',
       'criminal_damage_and_arson', 'drugs_rate', 'drugs', 'other_crime_rate',
       'other_crime', 'other_theft_rate', 'other_theft',
       'possession_of_weapons_rate', 'possession_of_weapons',
       'public_order_rate', 'public_order', 'robbery_rate', 'robbery',
       'shoplifting_rate', 'shoplifting', 'theft_from_the_person_rate',
       'theft_from_the_person', 'vehicle_crime_rate', 'vehicle_crime',
       'violence_and_sexual_offences_rate', 'violence_and_sexual_offences'],
      dtype='object')

**Drop Unrequired Columns**

In [67]:
claimant_clean = claimant[
    ["area_code", "pop", "claimant_rate"]
]

claimant_clean.columns

Index(['area_code', 'pop', 'claimant_rate'], dtype='object')

In [68]:
health_clean = health[
    [col for col in health.columns 
     if "prevalence_rate" in col 
     or col in ["area_code"]]
]

health_clean.columns

Index(['area_code', 'af_prevalence_rate', 'ast_prevalence_rate',
       'can_prevalence_rate', 'chd_prevalence_rate', 'ckd_prevalence_rate',
       'copd_prevalence_rate', 'dem_prevalence_rate', 'dep_prevalence_rate',
       'dm_prevalence_rate', 'ep_prevalence_rate', 'hf_prevalence_rate',
       'hyp_prevalence_rate', 'ld_prevalence_rate', 'mh_prevalence_rate',
       'ndh_prevalence_rate', 'ob_prevalence_rate', 'ost_prevalence_rate',
       'pad_prevalence_rate', 'pc_prevalence_rate', 'ra_prevalence_rate',
       'stia_prevalence_rate'],
      dtype='object')

In [69]:
crime_clean = crime[
    [col for col in crime.columns 
     if "rate" in col 
     or col in ["area_code"]]
]

crime_clean.columns

Index(['area_code', 'anti-social_behaviour_rate', 'bicycle_theft_rate',
       'burglary_rate', 'criminal_damage_and_arson_rate', 'drugs_rate',
       'other_crime_rate', 'other_theft_rate', 'possession_of_weapons_rate',
       'public_order_rate', 'robbery_rate', 'shoplifting_rate',
       'theft_from_the_person_rate', 'vehicle_crime_rate',
       'violence_and_sexual_offences_rate'],
      dtype='object')

**Check for Null Values**

In [70]:
display(claimant_clean.isnull().sum(), round(claimant_clean.isnull().mean(), 2)) # check the number of null values in each column and the percentage of null values in each column

area_code        0
pop              0
claimant_rate    0
dtype: int64

area_code        0.0
pop              0.0
claimant_rate    0.0
dtype: float64

In [71]:
display(health_clean.isnull().sum(), round(health_clean.isnull().mean(), 2))

area_code               0
af_prevalence_rate      0
ast_prevalence_rate     0
can_prevalence_rate     0
chd_prevalence_rate     0
ckd_prevalence_rate     0
copd_prevalence_rate    0
dem_prevalence_rate     0
dep_prevalence_rate     0
dm_prevalence_rate      0
ep_prevalence_rate      0
hf_prevalence_rate      0
hyp_prevalence_rate     0
ld_prevalence_rate      0
mh_prevalence_rate      0
ndh_prevalence_rate     0
ob_prevalence_rate      0
ost_prevalence_rate     0
pad_prevalence_rate     0
pc_prevalence_rate      0
ra_prevalence_rate      0
stia_prevalence_rate    0
dtype: int64

area_code               0.0
af_prevalence_rate      0.0
ast_prevalence_rate     0.0
can_prevalence_rate     0.0
chd_prevalence_rate     0.0
ckd_prevalence_rate     0.0
copd_prevalence_rate    0.0
dem_prevalence_rate     0.0
dep_prevalence_rate     0.0
dm_prevalence_rate      0.0
ep_prevalence_rate      0.0
hf_prevalence_rate      0.0
hyp_prevalence_rate     0.0
ld_prevalence_rate      0.0
mh_prevalence_rate      0.0
ndh_prevalence_rate     0.0
ob_prevalence_rate      0.0
ost_prevalence_rate     0.0
pad_prevalence_rate     0.0
pc_prevalence_rate      0.0
ra_prevalence_rate      0.0
stia_prevalence_rate    0.0
dtype: float64

In [72]:
display(crime_clean.isnull().sum(), round(crime_clean.isnull().mean(), 2))

area_code                            0
anti-social_behaviour_rate           0
bicycle_theft_rate                   0
burglary_rate                        0
criminal_damage_and_arson_rate       0
drugs_rate                           0
other_crime_rate                     0
other_theft_rate                     0
possession_of_weapons_rate           0
public_order_rate                    0
robbery_rate                         0
shoplifting_rate                     0
theft_from_the_person_rate           0
vehicle_crime_rate                   0
violence_and_sexual_offences_rate    0
dtype: int64

area_code                            0.0
anti-social_behaviour_rate           0.0
bicycle_theft_rate                   0.0
burglary_rate                        0.0
criminal_damage_and_arson_rate       0.0
drugs_rate                           0.0
other_crime_rate                     0.0
other_theft_rate                     0.0
possession_of_weapons_rate           0.0
public_order_rate                    0.0
robbery_rate                         0.0
shoplifting_rate                     0.0
theft_from_the_person_rate           0.0
vehicle_crime_rate                   0.0
violence_and_sexual_offences_rate    0.0
dtype: float64

**Remove duplicates**

In [73]:
# show rows with duplicates
claimant_clean[claimant_clean.duplicated(subset=["area_code"], keep=False)].sort_values(by="area_code").head() # check the rows with duplicate crime_id to understand if there are any patterns in the duplicates

Empty DataFrame
Columns: [area_code, pop, claimant_rate]
Index: []

In [74]:
# averaging duplicates
claimant_clean = (
    claimant_clean
    .groupby(["area_code", "pop"], as_index=False)
    .agg({"claimant_rate": "mean"})
)

claimant_clean["area_code"].duplicated().sum() # validate

np.int64(0)

In [75]:
health_clean[health_clean.duplicated(subset=["area_code"], keep=False)].sort_values(by="area_code").head()

Empty DataFrame
Columns: [area_code, af_prevalence_rate, ast_prevalence_rate, can_prevalence_rate, chd_prevalence_rate, ckd_prevalence_rate, copd_prevalence_rate, dem_prevalence_rate, dep_prevalence_rate, dm_prevalence_rate, ep_prevalence_rate, hf_prevalence_rate, hyp_prevalence_rate, ld_prevalence_rate, mh_prevalence_rate, ndh_prevalence_rate, ob_prevalence_rate, ost_prevalence_rate, pad_prevalence_rate, pc_prevalence_rate, ra_prevalence_rate, stia_prevalence_rate]
Index: []

[0 rows x 22 columns]

In [76]:
health_clean = (
    health_clean
    .groupby("area_code", as_index=False)
    .mean()
)

health_clean["area_code"].duplicated().sum()

np.int64(0)

In [77]:
crime_clean[crime_clean.duplicated(subset=["area_code"], keep=False)].sort_values(by="area_code").head()

Empty DataFrame
Columns: [area_code, anti-social_behaviour_rate, bicycle_theft_rate, burglary_rate, criminal_damage_and_arson_rate, drugs_rate, other_crime_rate, other_theft_rate, possession_of_weapons_rate, public_order_rate, robbery_rate, shoplifting_rate, theft_from_the_person_rate, vehicle_crime_rate, violence_and_sexual_offences_rate]
Index: []

In [78]:
crime_clean = (
    crime_clean
    .groupby("area_code", as_index=False)
    .mean()
)

crime_clean["area_code"].duplicated().sum()

np.int64(0)

**Feature Engineering**

In [79]:
# add all the prevelance rate

total_health_prevelance_rate = [col for col in health_clean.columns if col.endswith("_prevalence_rate")]

# Create total column
health_clean["total_prevalence_rate"] = health_clean[total_health_prevelance_rate].sum(axis=1)

health_clean.head()

,area_code,af_prevalence_rate,ast_prevalence_rate,can_prevalence_rate,chd_prevalence_rate,ckd_prevalence_rate,copd_prevalence_rate,dem_prevalence_rate,dep_prevalence_rate,dm_prevalence_rate,...,ld_prevalence_rate,mh_prevalence_rate,ndh_prevalence_rate,ob_prevalence_rate,ost_prevalence_rate,pad_prevalence_rate,pc_prevalence_rate,ra_prevalence_rate,stia_prevalence_rate,total_prevalence_rate
0,E01000001,0.012116,0.035175,0.021126,0.016198,0.021726,0.008768,0.002195,0.078826,0.029574,...,0.001277,0.009579,0.014849,0.028460,0.001633,0.003331,0.003133,0.004273,0.009583,0.396137
1,E01000002,0.012642,0.034753,0.021662,0.016508,0.022660,0.008737,0.002249,0.076197,0.029323,...,0.001166,0.009367,0.013701,0.028309,0.001755,0.003408,0.003227,0.004399,0.009774,0.395872
2,E01000003,0.011004,0.036276,0.019646,0.014895,0.018203,0.012799,0.002779,0.088891,0.032480,...,0.001845,0.010108,0.019377,0.031906,0.001272,0.003546,0.003133,0.003825,0.009129,0.412285
3,E01000005,0.008806,0.035617,0.016835,0.016930,0.022934,0.006007,0.001626,0.065815,0.047402,...,0.002527,0.011361,0.023103,0.025342,0.001427,0.002762,0.002280,0.004218,0.008819,0.392988
4,E01000006,0.008504,0.051032,0.016011,0.019437,0.013868,0.009929,0.003025,0.057886,0.074744,...,0.006045,0.008948,0.073888,0.046992,0.001140,0.002575,0.001803,0.006309,0.011146,0.530338

In [80]:
# add all the crime rate

total_crime_rate = [col for col in crime_clean.columns if col.endswith("_rate")]

# Create total column
crime_clean["total_crime_rate"] = crime_clean[total_crime_rate].sum(axis=1)

crime_clean.head()

,area_code,anti-social_behaviour_rate,bicycle_theft_rate,burglary_rate,criminal_damage_and_arson_rate,drugs_rate,other_crime_rate,other_theft_rate,possession_of_weapons_rate,public_order_rate,robbery_rate,shoplifting_rate,theft_from_the_person_rate,vehicle_crime_rate,violence_and_sexual_offences_rate,total_crime_rate
0,E01000001,0.021335,0.012388,0.003441,0.006882,0.008947,0.004818,0.021335,0.001376,0.004818,0.004129,0.008259,0.017894,0.024088,0.013076,0.152787
1,E01000002,0.041018,0.030410,0.004243,0.009194,0.007072,0.001414,0.023338,0.000707,0.012730,0.001414,0.009901,0.018388,0.004243,0.031825,0.195898
2,E01000003,0.021357,0.002513,0.000000,0.006281,0.002513,0.000628,0.001256,0.000000,0.001256,0.000000,0.000000,0.006281,0.001256,0.005025,0.048367
3,E01000005,0.057110,0.027413,0.017133,0.012564,0.027984,0.003427,0.034837,0.001142,0.017133,0.007424,0.013706,0.010851,0.015420,0.046830,0.292975
4,E01000006,0.033481,0.000000,0.002527,0.003159,0.012003,0.000000,0.001895,0.000000,0.001263,0.001895,0.000000,0.001895,0.006317,0.024005,0.088440

In [81]:
for df in dfs:
    print(df.dtypes)

area_code          object
area_name          object
pop                 int64
claimant_rate     float64
claimant_count      int64
dtype: object
area_code                object
area_name                object
pop                       int64
af_prevalence_rate      float64
af_afflicted            float64
ast_prevalence_rate     float64
ast_afflicted           float64
can_prevalence_rate     float64
can_afflicted           float64
chd_prevalence_rate     float64
chd_afflicted           float64
ckd_prevalence_rate     float64
ckd_afflicted           float64
copd_prevalence_rate    float64
copd_afflicted          float64
dem_prevalence_rate     float64
dem_afflicted           float64
dep_prevalence_rate     float64
dep_afflicted           float64
dm_prevalence_rate      float64
dm_afflicted            float64
ep_prevalence_rate      float64
ep_afflicted            float64
hf_prevalence_rate      float64
hf_afflicted            float64
hyp_prevalence_rate     float64
hyp_afflicted           float64
ld_prevalence_rate      float64
ld_afflicted            float64
mh_prevalence_rate      float64
mh_afflicted            float64
ndh_prevalence_rate     float64
ndh_afflicted           float64
ob_prevalence_rate      float64
ob_afflicted            float64
ost_prevalence_rate     float64
ost_afflicted           float64
pad_prevalence_rate     float64
pad_afflicted           float64
pc_prevalence_rate      float64
pc_afflicted            float64
ra_prevalence_rate      float64
ra_afflicted            float64
stia_prevalence_rate    float64
stia_afflicted          float64
dtype: object
area_code                             object
area_name                             object
pop                                    int64
anti-social_behaviour_rate           float64
anti-social_behaviour                  int64
bicycle_theft_rate                   float64
bicycle_theft                          int64
burglary_rate                        float64
burglary                               int64
criminal_damage_and_arson_rate       float64
criminal_damage_and_arson              int64
drugs_rate                           float64
drugs                                  int64
other_crime_rate                     float64
other_crime                            int64
other_theft_rate                     float64
other_theft                            int64
possession_of_weapons_rate           float64
possession_of_weapons                  int64
public_order_rate                    float64
public_order                           int64
robbery_rate                         float64
robbery                                int64
shoplifting_rate                     float64
shoplifting                            int64
theft_from_the_person_rate           float64
theft_from_the_person                  int64
vehicle_crime_rate                   float64
vehicle_crime                          int64
violence_and_sexual_offences_rate    float64
violence_and_sexual_offences           int64
dtype: object

**Export**

In [82]:
# Create the directory if it already doesn't exist
os.makedirs("../data/silver", exist_ok=True)

dfs = {
    "claimant_clean": claimant,
    "health_clean": health,
    "crime_clean": crime
}

for name, df in dfs.items():
    df.to_csv(f"../data/silver/{name}.csv", index=False)